# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stlproject/slt_repo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stlproject/slt_repo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stlproject/slt_repo/CMakeFiles /home/stlproject/slt_repo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stlproject/slt_repo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CaptureImages

# Build rule for target.
CaptureImages: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CaptureImages
.PHONY : CaptureImages

# fast build rule for target.
CaptureImages/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CaptureImages.dir/build.make CMakeFiles/CaptureImages.dir/build
.PHONY : CaptureImages/fast

#=============================================================================
# Target rules for targets named MainApp

# Build rule for target.
MainApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MainApp
.PHONY : MainApp

# fast build rule for target.
MainApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/build
.PHONY : MainApp/fast

#=============================================================================
# Target rules for targets named TrainApp

# Build rule for target.
TrainApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TrainApp
.PHONY : TrainApp

# fast build rule for target.
TrainApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrainApp.dir/build.make CMakeFiles/TrainApp.dir/build
.PHONY : TrainApp/fast

CameraManager.o: CameraManager.cpp.o
.PHONY : CameraManager.o

# target to build an object file
CameraManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/CameraManager.cpp.o
.PHONY : CameraManager.cpp.o

CameraManager.i: CameraManager.cpp.i
.PHONY : CameraManager.i

# target to preprocess a source file
CameraManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/CameraManager.cpp.i
.PHONY : CameraManager.cpp.i

CameraManager.s: CameraManager.cpp.s
.PHONY : CameraManager.s

# target to generate assembly for a file
CameraManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/CameraManager.cpp.s
.PHONY : CameraManager.cpp.s

GestureRecognizer.o: GestureRecognizer.cpp.o
.PHONY : GestureRecognizer.o

# target to build an object file
GestureRecognizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/GestureRecognizer.cpp.o
.PHONY : GestureRecognizer.cpp.o

GestureRecognizer.i: GestureRecognizer.cpp.i
.PHONY : GestureRecognizer.i

# target to preprocess a source file
GestureRecognizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/GestureRecognizer.cpp.i
.PHONY : GestureRecognizer.cpp.i

GestureRecognizer.s: GestureRecognizer.cpp.s
.PHONY : GestureRecognizer.s

# target to generate assembly for a file
GestureRecognizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/GestureRecognizer.cpp.s
.PHONY : GestureRecognizer.cpp.s

VoiceSynthesizer.o: VoiceSynthesizer.cpp.o
.PHONY : VoiceSynthesizer.o

# target to build an object file
VoiceSynthesizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/VoiceSynthesizer.cpp.o
.PHONY : VoiceSynthesizer.cpp.o

VoiceSynthesizer.i: VoiceSynthesizer.cpp.i
.PHONY : VoiceSynthesizer.i

# target to preprocess a source file
VoiceSynthesizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/VoiceSynthesizer.cpp.i
.PHONY : VoiceSynthesizer.cpp.i

VoiceSynthesizer.s: VoiceSynthesizer.cpp.s
.PHONY : VoiceSynthesizer.s

# target to generate assembly for a file
VoiceSynthesizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/VoiceSynthesizer.cpp.s
.PHONY : VoiceSynthesizer.cpp.s

capture_images.o: capture_images.cpp.o
.PHONY : capture_images.o

# target to build an object file
capture_images.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CaptureImages.dir/build.make CMakeFiles/CaptureImages.dir/capture_images.cpp.o
.PHONY : capture_images.cpp.o

capture_images.i: capture_images.cpp.i
.PHONY : capture_images.i

# target to preprocess a source file
capture_images.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CaptureImages.dir/build.make CMakeFiles/CaptureImages.dir/capture_images.cpp.i
.PHONY : capture_images.cpp.i

capture_images.s: capture_images.cpp.s
.PHONY : capture_images.s

# target to generate assembly for a file
capture_images.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CaptureImages.dir/build.make CMakeFiles/CaptureImages.dir/capture_images.cpp.s
.PHONY : capture_images.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MainApp.dir/build.make CMakeFiles/MainApp.dir/main.cpp.s
.PHONY : main.cpp.s

train.o: train.cpp.o
.PHONY : train.o

# target to build an object file
train.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrainApp.dir/build.make CMakeFiles/TrainApp.dir/train.cpp.o
.PHONY : train.cpp.o

train.i: train.cpp.i
.PHONY : train.i

# target to preprocess a source file
train.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrainApp.dir/build.make CMakeFiles/TrainApp.dir/train.cpp.i
.PHONY : train.cpp.i

train.s: train.cpp.s
.PHONY : train.s

# target to generate assembly for a file
train.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrainApp.dir/build.make CMakeFiles/TrainApp.dir/train.cpp.s
.PHONY : train.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CaptureImages"
	@echo "... MainApp"
	@echo "... TrainApp"
	@echo "... CameraManager.o"
	@echo "... CameraManager.i"
	@echo "... CameraManager.s"
	@echo "... GestureRecognizer.o"
	@echo "... GestureRecognizer.i"
	@echo "... GestureRecognizer.s"
	@echo "... VoiceSynthesizer.o"
	@echo "... VoiceSynthesizer.i"
	@echo "... VoiceSynthesizer.s"
	@echo "... capture_images.o"
	@echo "... capture_images.i"
	@echo "... capture_images.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... train.o"
	@echo "... train.i"
	@echo "... train.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

